[package]

name = "schedule_gen"
version = "0.0.1"
authors = [ "ethan.frei@gmail.com" ]

[lib]

name = "schedule_gen"

[dependencies]

uuid = {version = "0.2", features = ["v4"] }
chrono = "*"
rand = "*"
