[package]

name = "schedule_gen"
version = "0.0.1"
authors = [ "ethan.frei@gmail.com" ]

[lib]

name = "schedule_gen"

[dependencies.chrono]

git = "https://github.com/lifthrasiir/rust-chrono.git"

[dependencies.uuid]

git = "https://github.com/rust-lang/uuid.git"
